### ISSUE TITLE
Baidu Netdisk links  have expired

### ISSUE THREAD

**Issue by 3D3C** [HVision-NKU/Cascade-CLIP#1]
Hello,

Thank you very much for your work on Cascade-CLIP. It is excellent and has been very inspiring for me. However, the Baidu Netdisk links for the model weights of the PASCAL Context and COCO Stuff 164K datasets have expired. Could you please share them again?

Thank you!

**Comment by lyhisme** [comment]
Hello,

I'm glad to hear that you find Cascade-CLIP useful and inspiring! 

I apologize for the inconvenience caused by the expired links. I have updated the model weights for the PASCAL Context and COCO Stuff 164K datasets, and you can now access them through the following new [links](https://github.com/HVision-NKU/Cascade-CLIP/tree/main#pretrained-models).

Best regards!

**Comment by saimouli** [comment]
Could you also provide google drive link the links provided are broken
